/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class GUIHalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form GUIHalamanUtama
     */
    private boolean isPenjual = false;
    private ResultSet rs;
    private DataBase db = new DataBase();
    private int loginId;
    public GUIHalamanUtama(List<infoProduk> listNamaProduk) {
        initComponents();
        db.connect();
        rs = db.view("SELECT * FROM login");
        try{
            if(rs.next()){
                loginId = rs.getInt("id");
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        rs = db.view("SELECT * FROM penjual WHERE id = "+loginId+"");
        try{
            if(rs.next()){
                HalTokoButton.setVisible(true);
                BukaTokoButton.setVisible(false);
            }else{
                HalTokoButton.setVisible(false);
                BukaTokoButton.setVisible(true);
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        db.disconnect();
        loadData();
        addWhs.setVisible(false);
        DetailProdukButton.setVisible(false);
        tambahKeranjangButton.setVisible(false);
            this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DetailProdukButton.setVisible(false);
                tambahKeranjangButton.setVisible(false);
                addWhs.setVisible(false);
            }
        });

        TabelProduk.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (TabelProduk.getSelectedRow() >= 0) {
                    DetailProdukButton.setVisible(true);
                    tambahKeranjangButton.setVisible(true);
                    addWhs.setVisible(false);
                }
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelProduk = new javax.swing.JTable();
        ProfileButton = new javax.swing.JButton();
        WishlistButton = new javax.swing.JButton();
        KeranjangButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DetailProdukButton = new javax.swing.JButton();
        tambahKeranjangButton = new javax.swing.JButton();
        BukaTokoButton = new javax.swing.JButton();
        HalTokoButton = new javax.swing.JButton();
        addWhs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Produk", "Harga"
            }
        ));
        TabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelProduk);

        ProfileButton.setText("Profile");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        WishlistButton.setText("Wishlist");
        WishlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WishlistButtonActionPerformed(evt);
            }
        });

        KeranjangButton.setText("Keranjang");
        KeranjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeranjangButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("UREveryday");

        DetailProdukButton.setText("Lihat Detail Produk");
        DetailProdukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailProdukButtonActionPerformed(evt);
            }
        });

        tambahKeranjangButton.setText("+ Keranjang");
        tambahKeranjangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKeranjangButtonActionPerformed(evt);
            }
        });

        BukaTokoButton.setText("Buka Toko");
        BukaTokoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BukaTokoButtonActionPerformed(evt);
            }
        });

        HalTokoButton.setText("Halaman Toko");
        HalTokoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HalTokoButtonActionPerformed(evt);
            }
        });

        addWhs.setText("+Wishlist");
        addWhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HalTokoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(254, 254, 254))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(DetailProdukButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addWhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tambahKeranjangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(KeranjangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WishlistButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BukaTokoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HalTokoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WishlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KeranjangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BukaTokoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahKeranjangButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(addWhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DetailProdukButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        DialogSearch Search = new DialogSearch(this, true);
        Search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        GUIProfile profile = new GUIProfile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void WishlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WishlistButtonActionPerformed
        GUIWishlist wishlist = new GUIWishlist();
        wishlist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_WishlistButtonActionPerformed

    private void KeranjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeranjangButtonActionPerformed
        GUIKeranjang keranjang = new GUIKeranjang();
        keranjang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeranjangButtonActionPerformed

    private void TabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelProdukMouseClicked
       DetailProdukButton.setVisible(true);
       tambahKeranjangButton.setVisible(true);
    }//GEN-LAST:event_TabelProdukMouseClicked

    private void DetailProdukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailProdukButtonActionPerformed
        int selectedRow = TabelProduk.getSelectedRow();
        if (selectedRow >= 0) {
            String nama = (String) TabelProduk.getValueAt(selectedRow, 0);
            int harga = (int) TabelProduk.getValueAt(selectedRow, 1);

            GUIHalamanProduk dialog = new GUIHalamanProduk(nama, harga);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DetailProdukButtonActionPerformed

    private void tambahKeranjangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKeranjangButtonActionPerformed
        int selectedRow = TabelProduk.getSelectedRow();
        if (selectedRow >= 0) {
            String nama = (String) TabelProduk.getValueAt(selectedRow, 0);
            int harga = (int) TabelProduk.getValueAt(selectedRow, 1);
            
            int produkId = 0;
            
            db.connect();
            rs = db.view("SELECT * FROM produk WHERE nama = '"+nama+"'");
            try{
                if(rs.next()){
                    produkId = rs.getInt("Id");
                }
            }catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
            rs = db.view("SELECT * FROM wishlist WHERE idProduk = "+produkId+" AND idPembeli = "+loginId+"");
            try{
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Produk sudah ada di wishlist anda", "Message", JOptionPane.ERROR_MESSAGE);
                }else{
                    db.query("INSERT INTO wishlist(idPembeli, idProduk) VALUES ("+loginId+", "+produkId+")");
                    JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan ke wishlist anda", "Message", JOptionPane.INFORMATION_MESSAGE);
                    db.disconnect();
                }
            }catch(SQLException ex){
                System.out.println(ex.getMessage());
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahKeranjangButtonActionPerformed

    private void BukaTokoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BukaTokoButtonActionPerformed
        this.dispose();
        db.connect();
        rs = db.view("SELECT * FROM penjual WHERE id = "+loginId+"");
        try{
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Anda telah membuka toko", "Message", JOptionPane.INFORMATION_MESSAGE);
            }else{
                db.query("INSERT INTO penjual(id) VALUES ("+loginId+")");
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        GUIHalamanUtama HalU = new GUIHalamanUtama(null);
        HalU.setVisible(true);
    }//GEN-LAST:event_BukaTokoButtonActionPerformed

    private void HalTokoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HalTokoButtonActionPerformed
        GUIHalamanToko HalToko = new GUIHalamanToko();
        HalToko.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HalTokoButtonActionPerformed

    private void addWhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWhsActionPerformed
        int selectedRow = TabelProduk.getSelectedRow();
        if (selectedRow >= 0) {
            String nama = (String) TabelProduk.getValueAt(selectedRow, 0);
            int harga = (int) TabelProduk.getValueAt(selectedRow, 1);

            tambahKeranjang dialog = new tambahKeranjang(this, true, nama, harga);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addWhsActionPerformed

    private void loadData(){
        DataBase db = new DataBase();
        db.connect();
        ResultSet rs = db.view("SELECT * FROM produk");
        DefaultTableModel model = (DefaultTableModel) TabelProduk.getModel();
        model.setRowCount(0);
        try {
            while(rs.next()){
                Object[] row = new Object[2];
                row[0] = rs.getString("nama");
                row[1] = rs.getInt("harga");
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            db.disconnect();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHalamanUtama(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BukaTokoButton;
    private javax.swing.JButton DetailProdukButton;
    private javax.swing.JButton HalTokoButton;
    private javax.swing.JButton KeranjangButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable TabelProduk;
    private javax.swing.JButton WishlistButton;
    private javax.swing.JButton addWhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tambahKeranjangButton;
    // End of variables declaration//GEN-END:variables
}
