/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubespbo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author HP
 */
public class GUIProfile extends javax.swing.JFrame {

    /**
     * Creates new form GUIProfile
     */
    private Connection conn;
    private ResultSet rs;
    private DataBase db = new DataBase();
    private EditNama en = new EditNama(this, true);
    private EditAlamat ea = new EditAlamat(this, true);
    private EditNoHp enh = new EditNoHp(this, true);
    private EditPass ep = new EditPass(this, true);
    public GUIProfile() {
        initComponents();
        db.connect();
        rs = db.view("SELECT * FROM pembeli WHERE id = 1");
        try{
            while(rs.next()){
                NamaDisplay.setText("Nama    : " + rs.getString("nama"));
                NoTelpDisplay.setText("No. HP  : " + rs.getInt("noTelp"));
                AlamatDisplay.setText("Alamat   : " + rs.getString("alamat"));
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        db.disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NamaDisplay = new javax.swing.JLabel();
        NoTelpDisplay = new javax.swing.JLabel();
        AlamatDisplay = new javax.swing.JLabel();
        EditNama = new javax.swing.JButton();
        EditNoHp = new javax.swing.JButton();
        EditAlamat = new javax.swing.JButton();
        EditPass = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        BackButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Profile");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        NamaDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NamaDisplay.setText("Nama    : ");

        NoTelpDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoTelpDisplay.setText("No. HP  : ");

        AlamatDisplay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AlamatDisplay.setText("Alamat   : ");

        EditNama.setText("Edit");
        EditNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNamaActionPerformed(evt);
            }
        });

        EditNoHp.setText("Edit");
        EditNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditNoHpActionPerformed(evt);
            }
        });

        EditAlamat.setText("Edit");
        EditAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditAlamatActionPerformed(evt);
            }
        });

        EditPass.setText("Change Password");
        EditPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPassActionPerformed(evt);
            }
        });

        LogOutBtn.setText("Logout");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        BackButton2.setText("Back");
        BackButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlamatDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditAlamat))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NoTelpDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditNoHp))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NamaDisplay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditNama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton2)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89)))
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(EditPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaDisplay)
                    .addComponent(EditNama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoTelpDisplay)
                    .addComponent(EditNoHp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlamatDisplay)
                    .addComponent(EditAlamat))
                .addGap(18, 18, 18)
                .addComponent(EditPass)
                .addGap(18, 18, 18)
                .addComponent(LogOutBtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNamaActionPerformed
        en.setVisible(true);
        
    }//GEN-LAST:event_EditNamaActionPerformed

    private void EditNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditNoHpActionPerformed
        enh.setVisible(true);
    }//GEN-LAST:event_EditNoHpActionPerformed

    private void EditAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditAlamatActionPerformed
        ea.setVisible(true);
    }//GEN-LAST:event_EditAlamatActionPerformed

    private void EditPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPassActionPerformed
        ep.setVisible(true);
    }//GEN-LAST:event_EditPassActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        db.connect();
        rs = db.view("SELECT * FROM pembeli WHERE id = 1");
        try{
            while(rs.next()){
                NamaDisplay.setText("Nama    : " + rs.getString("nama"));
                NoTelpDisplay.setText("No. HP  : " + rs.getInt("noTelp"));
                AlamatDisplay.setText("Alamat   : " + rs.getString("alamat"));
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        db.disconnect(); 
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BackButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton2ActionPerformed
        GUIHalamanUtama HalamanUtama = new GUIHalamanUtama();
        HalamanUtama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlamatDisplay;
    private javax.swing.JButton BackButton2;
    private javax.swing.JButton EditAlamat;
    private javax.swing.JButton EditNama;
    private javax.swing.JButton EditNoHp;
    private javax.swing.JButton EditPass;
    private javax.swing.JButton LogOutBtn;
    public javax.swing.JLabel NamaDisplay;
    private javax.swing.JLabel NoTelpDisplay;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
